In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from ml_library import DecisionTreeClassifier , train_test_split , z_score_normalization

In [2]:
df = pd.read_csv("./dataset/train_binary.csv")
df.shape

(50000, 26)

In [3]:
df.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,label
0,515.552122,0.501142,5333.319937,172.962979,0.004575,46549.221548,502.584920,0.458395,4625.879935,151.521484,...,144.258303,0.789506,2865.992302,160.440862,0.694201,1694.929183,1.496844,0.146772,1.0,1
1,668.286985,0.508581,4370.282875,128.300296,0.004639,44025.018827,636.168692,0.467422,3879.914621,107.274618,...,62.304522,1.017827,2472.959367,124.381135,0.401894,2443.117516,0.846703,0.215638,1.0,0
2,517.168489,0.483042,3326.280886,75.704752,0.004040,52406.140385,492.702393,0.444783,2869.670905,60.559518,...,111.695965,0.861554,1790.204707,153.325634,0.813255,1469.394258,1.742825,-0.231080,-1.0,1
3,417.096784,0.487056,6286.092355,102.207298,0.004742,36243.588753,397.695808,0.447867,5592.085691,81.986835,...,35.834294,0.921524,2881.303663,90.376685,0.253066,2684.461934,1.286850,0.354612,1.0,0
4,427.939556,0.498989,3768.307841,124.954769,0.004527,45977.266327,417.109675,0.460051,3413.620214,88.142404,...,71.319597,0.898992,3037.465775,163.221910,0.877538,1387.321736,1.328970,0.190285,1.0,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 26 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   feature_0   50000 non-null  float64
 1   feature_1   50000 non-null  float64
 2   feature_2   50000 non-null  float64
 3   feature_3   50000 non-null  float64
 4   feature_4   50000 non-null  float64
 5   feature_5   50000 non-null  float64
 6   feature_6   50000 non-null  float64
 7   feature_7   50000 non-null  float64
 8   feature_8   50000 non-null  float64
 9   feature_9   50000 non-null  float64
 10  feature_10  50000 non-null  float64
 11  feature_11  50000 non-null  float64
 12  feature_12  50000 non-null  float64
 13  feature_13  50000 non-null  float64
 14  feature_14  50000 non-null  float64
 15  feature_15  50000 non-null  float64
 16  feature_16  50000 non-null  float64
 17  feature_17  50000 non-null  float64
 18  feature_18  50000 non-null  float64
 19  feature_19  50000 non-null  float64
 20  feature_20  50000 non-null  float64
 21  feature_21  50000 non-null  float64
 22  feature_22  50000 non-null  float64
 23  feature_23  50000 non-null  float64
 24  feature_24  50000 non-null  float64
 25  label       50000 non-null  int64
dtypes: float64(25), int64(1)
memory usage: 9.9 MB

In [5]:
X = df.drop("label", axis=1).values
y = df["label"].values.reshape(-1,1)
X.shape, y.shape

((50000, 25), (50000, 1))

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train = z_score_normalization(X_train)
X_test = z_score_normalization(X_test)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((40000, 25), (10000, 25), (40000, 1), (10000, 1))

In [7]:
model = DecisionTreeClassifier(min_sample_split=3 , max_depth= 3)
model.fit(X_train, y_train)

In [19]:
y_pred = model.predict(X_test)
y_pred = np.array(y_pred, dtype=int)
y_test = y_test.reshape(-1)
model.evaluation_metrics(y_test , y_pred)

Accuracy: 0.998
Precision: 0.998342175066313
Recall: 0.9950429610046265
F1 Score: 0.9966898378020523
Confusion Matrix: [[6969    5]
 [  15 3011]]

(np.float64(0.998),
 np.float64(0.998342175066313),
 np.float64(0.9950429610046265),
 np.float64(0.9966898378020523),
 array([[6969,    5],
        [  15, 3011]]))

In [20]:
df_test = pd.read_csv("./dataset/test_binary.csv")
df_test.shape

(25000, 25)

In [21]:
df_test.sample(5)

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24
8563,392.241001,0.500925,4712.590994,150.535581,0.004033,35825.279120,369.481430,0.458930,4206.895370,123.212867,...,10.428758,75.832046,0.873160,3293.315699,180.773633,0.358696,1111.807908,1.050782,1.370968,-1.0
13531,447.042396,0.489691,3899.660696,170.485571,0.005152,46263.154868,423.254029,0.453353,3381.631970,129.127938,...,7.345584,76.449029,1.069948,1551.390386,276.601900,0.283766,816.770233,1.788304,-0.056860,1.0
16276,545.446688,0.515228,5487.107562,62.375687,0.004165,53108.143616,523.356694,0.473266,4756.281129,45.938655,...,6.815181,106.879745,1.057021,3008.977182,118.247792,0.361996,2414.492437,0.896387,-0.259659,1.0
11849,359.024826,0.486524,4734.164091,94.728282,0.005881,57835.626906,345.830238,0.448383,4154.578072,82.728611,...,11.915334,58.352282,0.995640,2063.736396,130.418179,0.357937,1001.237841,0.285981,0.690399,1.0
12868,385.408275,0.506046,5397.554235,92.982043,0.005514,43437.754332,372.586747,0.466512,4787.635623,80.086898,...,10.751359,82.506055,0.827676,2084.375991,292.802584,0.337915,549.756987,0.421604,-0.337508,-1.0

In [22]:
X_testing = df_test.values
X_testing = z_score_normalization(X_testing)

In [24]:
y_pred_test = model.predict(X_testing)
y_pred_test = np.array(y_pred_test, dtype=int)
y_pred_test

array([1, 0, 0, ..., 0, 0, 0], shape=(25000,))

In [25]:
df_test["label"] = y_pred_test
df_test.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,label
0,425.961417,0.499021,5534.216993,158.937483,0.003203,40326.757559,392.911630,0.462618,4839.965545,109.779291,...,48.159841,1.055733,2512.532685,81.660268,0.389696,722.416800,1.294156,1.738285,1.0,1
1,621.169873,0.491361,5451.920192,134.151060,0.004912,46801.608384,586.622737,0.451685,4652.116744,123.802102,...,89.110342,1.121912,2878.217512,193.418479,0.367436,1044.469536,0.818993,0.028234,-1.0,0
2,674.759463,0.497538,4353.708167,144.341660,0.005261,18439.406062,641.720752,0.460264,3963.570118,130.214181,...,52.844750,0.976829,2379.556453,208.435965,0.344384,377.734099,1.097345,-0.824431,-1.0,0
3,555.548489,0.515458,5888.622134,126.766461,0.004454,31774.488278,536.516886,0.474615,5151.605518,94.595414,...,115.401214,0.701615,2546.142182,170.688107,0.327638,588.388582,1.037413,0.995409,1.0,0
4,561.974757,0.494302,5505.669060,109.243006,0.004877,58478.356459,540.144512,0.458056,4862.586548,85.480364,...,83.822568,0.801240,2843.177513,239.436877,0.310055,388.434472,0.538400,-0.104211,-1.0,0

In [26]:
df_test.to_csv("./output/predictions_decision_tree_classifier.csv", index=False)